// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add_group_member_request.proto

package win.liyufan.im.proto;

public final class AddGroupMemberRequestOuterClass {
  private AddGroupMemberRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddGroupMemberRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mars.stn.AddGroupMemberRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string group_id = 1;</code>
     */
    java.lang.String getGroupId();
    /**
     * <code>string group_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
     */
    java.util.List<win.liyufan.im.proto.GroupOuterClass.GroupMember> 
        getAddedMemberList();
    /**
     * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
     */
    win.liyufan.im.proto.GroupOuterClass.GroupMember getAddedMember(int index);
    /**
     * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
     */
    int getAddedMemberCount();
    /**
     * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
     */
    java.util.List<? extends win.liyufan.im.proto.GroupOuterClass.GroupMemberOrBuilder> 
        getAddedMemberOrBuilderList();
    /**
     * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
     */
    win.liyufan.im.proto.GroupOuterClass.GroupMemberOrBuilder getAddedMemberOrBuilder(
        int index);

    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    java.util.List<java.lang.Integer> getToLineList();
    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    int getToLineCount();
    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    int getToLine(int index);

    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    boolean hasNotifyContent();
    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    win.liyufan.im.proto.MessageContentOuterClass.MessageContent getNotifyContent();
    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder getNotifyContentOrBuilder();
  }
  /**
   * Protobuf type {@code mars.stn.AddGroupMemberRequest}
   */
  public  static final class AddGroupMemberRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mars.stn.AddGroupMemberRequest)
      AddGroupMemberRequestOrBuilder {
    // Use AddGroupMemberRequest.newBuilder() to construct.
    private AddGroupMemberRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddGroupMemberRequest() {
      groupId_ = "";
      addedMember_ = java.util.Collections.emptyList();
      toLine_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AddGroupMemberRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                addedMember_ = new java.util.ArrayList<win.liyufan.im.proto.GroupOuterClass.GroupMember>();
                mutable_bitField0_ |= 0x00000002;
              }
              addedMember_.add(
                  input.readMessage(win.liyufan.im.proto.GroupOuterClass.GroupMember.parser(), extensionRegistry));
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                toLine_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              toLine_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                toLine_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                toLine_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder subBuilder = null;
              if (notifyContent_ != null) {
                subBuilder = notifyContent_.toBuilder();
              }
              notifyContent_ = input.readMessage(win.liyufan.im.proto.MessageContentOuterClass.MessageContent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(notifyContent_);
                notifyContent_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          addedMember_ = java.util.Collections.unmodifiableList(addedMember_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          toLine_ = java.util.Collections.unmodifiableList(toLine_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.AddGroupMemberRequestOuterClass.internal_static_mars_stn_AddGroupMemberRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.AddGroupMemberRequestOuterClass.internal_static_mars_stn_AddGroupMemberRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest.class, win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest.Builder.class);
    }

    private int bitField0_;
    public static final int GROUP_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object groupId_;
    /**
     * <code>string group_id = 1;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <code>string group_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDED_MEMBER_FIELD_NUMBER = 2;
    private java.util.List<win.liyufan.im.proto.GroupOuterClass.GroupMember> addedMember_;
    /**
     * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
     */
    public java.util.List<win.liyufan.im.proto.GroupOuterClass.GroupMember> getAddedMemberList() {
      return addedMember_;
    }
    /**
     * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
     */
    public java.util.List<? extends win.liyufan.im.proto.GroupOuterClass.GroupMemberOrBuilder> 
        getAddedMemberOrBuilderList() {
      return addedMember_;
    }
    /**
     * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
     */
    public int getAddedMemberCount() {
      return addedMember_.size();
    }
    /**
     * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
     */
    public win.liyufan.im.proto.GroupOuterClass.GroupMember getAddedMember(int index) {
      return addedMember_.get(index);
    }
    /**
     * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
     */
    public win.liyufan.im.proto.GroupOuterClass.GroupMemberOrBuilder getAddedMemberOrBuilder(
        int index) {
      return addedMember_.get(index);
    }

    public static final int TO_LINE_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> toLine_;
    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getToLineList() {
      return toLine_;
    }
    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    public int getToLineCount() {
      return toLine_.size();
    }
    /**
     * <code>repeated int32 to_line = 3;</code>
     */
    public int getToLine(int index) {
      return toLine_.get(index);
    }
    private int toLineMemoizedSerializedSize = -1;

    public static final int NOTIFY_CONTENT_FIELD_NUMBER = 4;
    private win.liyufan.im.proto.MessageContentOuterClass.MessageContent notifyContent_;
    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    public boolean hasNotifyContent() {
      return notifyContent_ != null;
    }
    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    public win.liyufan.im.proto.MessageContentOuterClass.MessageContent getNotifyContent() {
      return notifyContent_ == null ? win.liyufan.im.proto.MessageContentOuterClass.MessageContent.getDefaultInstance() : notifyContent_;
    }
    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    public win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder getNotifyContentOrBuilder() {
      return getNotifyContent();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, groupId_);
      }
      for (int i = 0; i < addedMember_.size(); i++) {
        output.writeMessage(2, addedMember_.get(i));
      }
      if (getToLineList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(toLineMemoizedSerializedSize);
      }
      for (int i = 0; i < toLine_.size(); i++) {
        output.writeInt32NoTag(toLine_.get(i));
      }
      if (notifyContent_ != null) {
        output.writeMessage(4, getNotifyContent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, groupId_);
      }
      for (int i = 0; i < addedMember_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, addedMember_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < toLine_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(toLine_.get(i));
        }
        size += dataSize;
        if (!getToLineList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        toLineMemoizedSerializedSize = dataSize;
      }
      if (notifyContent_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getNotifyContent());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest other = (win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest) obj;

      boolean result = true;
      result = result && getGroupId()
          .equals(other.getGroupId());
      result = result && getAddedMemberList()
          .equals(other.getAddedMemberList());
      result = result && getToLineList()
          .equals(other.getToLineList());
      result = result && (hasNotifyContent() == other.hasNotifyContent());
      if (hasNotifyContent()) {
        result = result && getNotifyContent()
            .equals(other.getNotifyContent());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      if (getAddedMemberCount() > 0) {
        hash = (37 * hash) + ADDED_MEMBER_FIELD_NUMBER;
        hash = (53 * hash) + getAddedMemberList().hashCode();
      }
      if (getToLineCount() > 0) {
        hash = (37 * hash) + TO_LINE_FIELD_NUMBER;
        hash = (53 * hash) + getToLineList().hashCode();
      }
      if (hasNotifyContent()) {
        hash = (37 * hash) + NOTIFY_CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getNotifyContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mars.stn.AddGroupMemberRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mars.stn.AddGroupMemberRequest)
        win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.AddGroupMemberRequestOuterClass.internal_static_mars_stn_AddGroupMemberRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.AddGroupMemberRequestOuterClass.internal_static_mars_stn_AddGroupMemberRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest.class, win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest.Builder.class);
      }

      // Construct using win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddedMemberFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        groupId_ = "";

        if (addedMemberBuilder_ == null) {
          addedMember_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          addedMemberBuilder_.clear();
        }
        toLine_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        if (notifyContentBuilder_ == null) {
          notifyContent_ = null;
        } else {
          notifyContent_ = null;
          notifyContentBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.AddGroupMemberRequestOuterClass.internal_static_mars_stn_AddGroupMemberRequest_descriptor;
      }

      public win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest getDefaultInstanceForType() {
        return win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest.getDefaultInstance();
      }

      public win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest build() {
        win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest buildPartial() {
        win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest result = new win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.groupId_ = groupId_;
        if (addedMemberBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            addedMember_ = java.util.Collections.unmodifiableList(addedMember_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.addedMember_ = addedMember_;
        } else {
          result.addedMember_ = addedMemberBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          toLine_ = java.util.Collections.unmodifiableList(toLine_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.toLine_ = toLine_;
        if (notifyContentBuilder_ == null) {
          result.notifyContent_ = notifyContent_;
        } else {
          result.notifyContent_ = notifyContentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest) {
          return mergeFrom((win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest other) {
        if (other == win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest.getDefaultInstance()) return this;
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (addedMemberBuilder_ == null) {
          if (!other.addedMember_.isEmpty()) {
            if (addedMember_.isEmpty()) {
              addedMember_ = other.addedMember_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAddedMemberIsMutable();
              addedMember_.addAll(other.addedMember_);
            }
            onChanged();
          }
        } else {
          if (!other.addedMember_.isEmpty()) {
            if (addedMemberBuilder_.isEmpty()) {
              addedMemberBuilder_.dispose();
              addedMemberBuilder_ = null;
              addedMember_ = other.addedMember_;
              bitField0_ = (bitField0_ & ~0x00000002);
              addedMemberBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAddedMemberFieldBuilder() : null;
            } else {
              addedMemberBuilder_.addAllMessages(other.addedMember_);
            }
          }
        }
        if (!other.toLine_.isEmpty()) {
          if (toLine_.isEmpty()) {
            toLine_ = other.toLine_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureToLineIsMutable();
            toLine_.addAll(other.toLine_);
          }
          onChanged();
        }
        if (other.hasNotifyContent()) {
          mergeNotifyContent(other.getNotifyContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object groupId_ = "";
      /**
       * <code>string group_id = 1;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string group_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group_id = 1;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string group_id = 1;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <code>string group_id = 1;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<win.liyufan.im.proto.GroupOuterClass.GroupMember> addedMember_ =
        java.util.Collections.emptyList();
      private void ensureAddedMemberIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          addedMember_ = new java.util.ArrayList<win.liyufan.im.proto.GroupOuterClass.GroupMember>(addedMember_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          win.liyufan.im.proto.GroupOuterClass.GroupMember, win.liyufan.im.proto.GroupOuterClass.GroupMember.Builder, win.liyufan.im.proto.GroupOuterClass.GroupMemberOrBuilder> addedMemberBuilder_;

      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public java.util.List<win.liyufan.im.proto.GroupOuterClass.GroupMember> getAddedMemberList() {
        if (addedMemberBuilder_ == null) {
          return java.util.Collections.unmodifiableList(addedMember_);
        } else {
          return addedMemberBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public int getAddedMemberCount() {
        if (addedMemberBuilder_ == null) {
          return addedMember_.size();
        } else {
          return addedMemberBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.GroupMember getAddedMember(int index) {
        if (addedMemberBuilder_ == null) {
          return addedMember_.get(index);
        } else {
          return addedMemberBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public Builder setAddedMember(
          int index, win.liyufan.im.proto.GroupOuterClass.GroupMember value) {
        if (addedMemberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddedMemberIsMutable();
          addedMember_.set(index, value);
          onChanged();
        } else {
          addedMemberBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public Builder setAddedMember(
          int index, win.liyufan.im.proto.GroupOuterClass.GroupMember.Builder builderForValue) {
        if (addedMemberBuilder_ == null) {
          ensureAddedMemberIsMutable();
          addedMember_.set(index, builderForValue.build());
          onChanged();
        } else {
          addedMemberBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public Builder addAddedMember(win.liyufan.im.proto.GroupOuterClass.GroupMember value) {
        if (addedMemberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddedMemberIsMutable();
          addedMember_.add(value);
          onChanged();
        } else {
          addedMemberBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public Builder addAddedMember(
          int index, win.liyufan.im.proto.GroupOuterClass.GroupMember value) {
        if (addedMemberBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAddedMemberIsMutable();
          addedMember_.add(index, value);
          onChanged();
        } else {
          addedMemberBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public Builder addAddedMember(
          win.liyufan.im.proto.GroupOuterClass.GroupMember.Builder builderForValue) {
        if (addedMemberBuilder_ == null) {
          ensureAddedMemberIsMutable();
          addedMember_.add(builderForValue.build());
          onChanged();
        } else {
          addedMemberBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public Builder addAddedMember(
          int index, win.liyufan.im.proto.GroupOuterClass.GroupMember.Builder builderForValue) {
        if (addedMemberBuilder_ == null) {
          ensureAddedMemberIsMutable();
          addedMember_.add(index, builderForValue.build());
          onChanged();
        } else {
          addedMemberBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public Builder addAllAddedMember(
          java.lang.Iterable<? extends win.liyufan.im.proto.GroupOuterClass.GroupMember> values) {
        if (addedMemberBuilder_ == null) {
          ensureAddedMemberIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, addedMember_);
          onChanged();
        } else {
          addedMemberBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public Builder clearAddedMember() {
        if (addedMemberBuilder_ == null) {
          addedMember_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          addedMemberBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public Builder removeAddedMember(int index) {
        if (addedMemberBuilder_ == null) {
          ensureAddedMemberIsMutable();
          addedMember_.remove(index);
          onChanged();
        } else {
          addedMemberBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.GroupMember.Builder getAddedMemberBuilder(
          int index) {
        return getAddedMemberFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.GroupMemberOrBuilder getAddedMemberOrBuilder(
          int index) {
        if (addedMemberBuilder_ == null) {
          return addedMember_.get(index);  } else {
          return addedMemberBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public java.util.List<? extends win.liyufan.im.proto.GroupOuterClass.GroupMemberOrBuilder> 
           getAddedMemberOrBuilderList() {
        if (addedMemberBuilder_ != null) {
          return addedMemberBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(addedMember_);
        }
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.GroupMember.Builder addAddedMemberBuilder() {
        return getAddedMemberFieldBuilder().addBuilder(
            win.liyufan.im.proto.GroupOuterClass.GroupMember.getDefaultInstance());
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.GroupMember.Builder addAddedMemberBuilder(
          int index) {
        return getAddedMemberFieldBuilder().addBuilder(
            index, win.liyufan.im.proto.GroupOuterClass.GroupMember.getDefaultInstance());
      }
      /**
       * <code>repeated .mars.stn.GroupMember added_member = 2;</code>
       */
      public java.util.List<win.liyufan.im.proto.GroupOuterClass.GroupMember.Builder> 
           getAddedMemberBuilderList() {
        return getAddedMemberFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          win.liyufan.im.proto.GroupOuterClass.GroupMember, win.liyufan.im.proto.GroupOuterClass.GroupMember.Builder, win.liyufan.im.proto.GroupOuterClass.GroupMemberOrBuilder> 
          getAddedMemberFieldBuilder() {
        if (addedMemberBuilder_ == null) {
          addedMemberBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              win.liyufan.im.proto.GroupOuterClass.GroupMember, win.liyufan.im.proto.GroupOuterClass.GroupMember.Builder, win.liyufan.im.proto.GroupOuterClass.GroupMemberOrBuilder>(
                  addedMember_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          addedMember_ = null;
        }
        return addedMemberBuilder_;
      }

      private java.util.List<java.lang.Integer> toLine_ = java.util.Collections.emptyList();
      private void ensureToLineIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          toLine_ = new java.util.ArrayList<java.lang.Integer>(toLine_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getToLineList() {
        return java.util.Collections.unmodifiableList(toLine_);
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public int getToLineCount() {
        return toLine_.size();
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public int getToLine(int index) {
        return toLine_.get(index);
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public Builder setToLine(
          int index, int value) {
        ensureToLineIsMutable();
        toLine_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public Builder addToLine(int value) {
        ensureToLineIsMutable();
        toLine_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public Builder addAllToLine(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureToLineIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, toLine_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 to_line = 3;</code>
       */
      public Builder clearToLine() {
        toLine_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private win.liyufan.im.proto.MessageContentOuterClass.MessageContent notifyContent_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.MessageContentOuterClass.MessageContent, win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder, win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder> notifyContentBuilder_;
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public boolean hasNotifyContent() {
        return notifyContentBuilder_ != null || notifyContent_ != null;
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public win.liyufan.im.proto.MessageContentOuterClass.MessageContent getNotifyContent() {
        if (notifyContentBuilder_ == null) {
          return notifyContent_ == null ? win.liyufan.im.proto.MessageContentOuterClass.MessageContent.getDefaultInstance() : notifyContent_;
        } else {
          return notifyContentBuilder_.getMessage();
        }
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public Builder setNotifyContent(win.liyufan.im.proto.MessageContentOuterClass.MessageContent value) {
        if (notifyContentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          notifyContent_ = value;
          onChanged();
        } else {
          notifyContentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public Builder setNotifyContent(
          win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder builderForValue) {
        if (notifyContentBuilder_ == null) {
          notifyContent_ = builderForValue.build();
          onChanged();
        } else {
          notifyContentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public Builder mergeNotifyContent(win.liyufan.im.proto.MessageContentOuterClass.MessageContent value) {
        if (notifyContentBuilder_ == null) {
          if (notifyContent_ != null) {
            notifyContent_ =
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent.newBuilder(notifyContent_).mergeFrom(value).buildPartial();
          } else {
            notifyContent_ = value;
          }
          onChanged();
        } else {
          notifyContentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public Builder clearNotifyContent() {
        if (notifyContentBuilder_ == null) {
          notifyContent_ = null;
          onChanged();
        } else {
          notifyContent_ = null;
          notifyContentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder getNotifyContentBuilder() {
        
        onChanged();
        return getNotifyContentFieldBuilder().getBuilder();
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder getNotifyContentOrBuilder() {
        if (notifyContentBuilder_ != null) {
          return notifyContentBuilder_.getMessageOrBuilder();
        } else {
          return notifyContent_ == null ?
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent.getDefaultInstance() : notifyContent_;
        }
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.MessageContentOuterClass.MessageContent, win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder, win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder> 
          getNotifyContentFieldBuilder() {
        if (notifyContentBuilder_ == null) {
          notifyContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent, win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder, win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder>(
                  getNotifyContent(),
                  getParentForChildren(),
                  isClean());
          notifyContent_ = null;
        }
        return notifyContentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mars.stn.AddGroupMemberRequest)
    }

    // @@protoc_insertion_point(class_scope:mars.stn.AddGroupMemberRequest)
    private static final win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest();
    }

    public static win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddGroupMemberRequest>
        PARSER = new com.google.protobuf.AbstractParser<AddGroupMemberRequest>() {
      public AddGroupMemberRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AddGroupMemberRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddGroupMemberRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddGroupMemberRequest> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.AddGroupMemberRequestOuterClass.AddGroupMemberRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mars_stn_AddGroupMemberRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mars_stn_AddGroupMemberRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036add_group_member_request.proto\022\010mars.s" +
      "tn\032\025message_content.proto\032\013group.proto\"\231" +
      "\001\n\025AddGroupMemberRequest\022\020\n\010group_id\030\001 \001" +
      "(\t\022+\n\014added_member\030\002 \003(\0132\025.mars.stn.Grou" +
      "pMember\022\017\n\007to_line\030\003 \003(\005\0220\n\016notify_conte" +
      "nt\030\004 \001(\0132\030.mars.stn.MessageContentB7\n\024wi" +
      "n.liyufan.im.protoB\037AddGroupMemberReques" +
      "tOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          win.liyufan.im.proto.MessageContentOuterClass.getDescriptor(),
          win.liyufan.im.proto.GroupOuterClass.getDescriptor(),
        }, assigner);
    internal_static_mars_stn_AddGroupMemberRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mars_stn_AddGroupMemberRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mars_stn_AddGroupMemberRequest_descriptor,
        new java.lang.String[] { "GroupId", "AddedMember", "ToLine", "NotifyContent", });
    win.liyufan.im.proto.MessageContentOuterClass.getDescriptor();
    win.liyufan.im.proto.GroupOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
