// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: group.proto

package win.liyufan.im.proto;

public final class GroupOuterClass {
  private GroupOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code mars.stn.GroupType}
   */
  public enum GroupType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *member can add quit change group name and portrait, owner can do all the operations
     * </pre>
     *
     * <code>GroupType_Normal = 0;</code>
     */
    GroupType_Normal(0),
    /**
     * <pre>
     *every member can add quit change group name and portrait, no one can kickoff others
     * </pre>
     *
     * <code>GroupType_Free = 1;</code>
     */
    GroupType_Free(1),
    /**
     * <pre>
     *member can only quit, owner can do all the operations
     * </pre>
     *
     * <code>GroupType_Restricted = 2;</code>
     */
    GroupType_Restricted(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *member can add quit change group name and portrait, owner can do all the operations
     * </pre>
     *
     * <code>GroupType_Normal = 0;</code>
     */
    public static final int GroupType_Normal_VALUE = 0;
    /**
     * <pre>
     *every member can add quit change group name and portrait, no one can kickoff others
     * </pre>
     *
     * <code>GroupType_Free = 1;</code>
     */
    public static final int GroupType_Free_VALUE = 1;
    /**
     * <pre>
     *member can only quit, owner can do all the operations
     * </pre>
     *
     * <code>GroupType_Restricted = 2;</code>
     */
    public static final int GroupType_Restricted_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GroupType valueOf(int value) {
      return forNumber(value);
    }

    public static GroupType forNumber(int value) {
      switch (value) {
        case 0: return GroupType_Normal;
        case 1: return GroupType_Free;
        case 2: return GroupType_Restricted;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GroupType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GroupType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GroupType>() {
            public GroupType findValueByNumber(int number) {
              return GroupType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return win.liyufan.im.proto.GroupOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final GroupType[] VALUES = values();

    public static GroupType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GroupType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:mars.stn.GroupType)
  }

  public interface GroupInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mars.stn.GroupInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string target_id = 1;</code>
     */
    java.lang.String getTargetId();
    /**
     * <code>string target_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getTargetIdBytes();

    /**
     * <code>int32 line = 2;</code>
     */
    int getLine();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string portrait = 4;</code>
     */
    java.lang.String getPortrait();
    /**
     * <code>string portrait = 4;</code>
     */
    com.google.protobuf.ByteString
        getPortraitBytes();

    /**
     * <code>string owner = 5;</code>
     */
    java.lang.String getOwner();
    /**
     * <code>string owner = 5;</code>
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>.mars.stn.GroupType type = 6;</code>
     */
    int getTypeValue();
    /**
     * <code>.mars.stn.GroupType type = 6;</code>
     */
    win.liyufan.im.proto.GroupOuterClass.GroupType getType();

    /**
     * <code>string extra = 7;</code>
     */
    java.lang.String getExtra();
    /**
     * <code>string extra = 7;</code>
     */
    com.google.protobuf.ByteString
        getExtraBytes();

    /**
     * <code>int64 update_dt = 8;</code>
     */
    long getUpdateDt();
  }
  /**
   * Protobuf type {@code mars.stn.GroupInfo}
   */
  public  static final class GroupInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mars.stn.GroupInfo)
      GroupInfoOrBuilder {
    // Use GroupInfo.newBuilder() to construct.
    private GroupInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GroupInfo() {
      targetId_ = "";
      line_ = 0;
      name_ = "";
      portrait_ = "";
      owner_ = "";
      type_ = 0;
      extra_ = "";
      updateDt_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GroupInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              targetId_ = s;
              break;
            }
            case 16: {

              line_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              portrait_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              owner_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              extra_ = s;
              break;
            }
            case 64: {

              updateDt_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.GroupOuterClass.internal_static_mars_stn_GroupInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.GroupOuterClass.internal_static_mars_stn_GroupInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.GroupOuterClass.GroupInfo.class, win.liyufan.im.proto.GroupOuterClass.GroupInfo.Builder.class);
    }

    public static final int TARGET_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object targetId_;
    /**
     * <code>string target_id = 1;</code>
     */
    public java.lang.String getTargetId() {
      java.lang.Object ref = targetId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetId_ = s;
        return s;
      }
    }
    /**
     * <code>string target_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTargetIdBytes() {
      java.lang.Object ref = targetId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LINE_FIELD_NUMBER = 2;
    private int line_;
    /**
     * <code>int32 line = 2;</code>
     */
    public int getLine() {
      return line_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORTRAIT_FIELD_NUMBER = 4;
    private volatile java.lang.Object portrait_;
    /**
     * <code>string portrait = 4;</code>
     */
    public java.lang.String getPortrait() {
      java.lang.Object ref = portrait_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        portrait_ = s;
        return s;
      }
    }
    /**
     * <code>string portrait = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPortraitBytes() {
      java.lang.Object ref = portrait_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        portrait_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OWNER_FIELD_NUMBER = 5;
    private volatile java.lang.Object owner_;
    /**
     * <code>string owner = 5;</code>
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        owner_ = s;
        return s;
      }
    }
    /**
     * <code>string owner = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_;
    /**
     * <code>.mars.stn.GroupType type = 6;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.mars.stn.GroupType type = 6;</code>
     */
    public win.liyufan.im.proto.GroupOuterClass.GroupType getType() {
      win.liyufan.im.proto.GroupOuterClass.GroupType result = win.liyufan.im.proto.GroupOuterClass.GroupType.valueOf(type_);
      return result == null ? win.liyufan.im.proto.GroupOuterClass.GroupType.UNRECOGNIZED : result;
    }

    public static final int EXTRA_FIELD_NUMBER = 7;
    private volatile java.lang.Object extra_;
    /**
     * <code>string extra = 7;</code>
     */
    public java.lang.String getExtra() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extra_ = s;
        return s;
      }
    }
    /**
     * <code>string extra = 7;</code>
     */
    public com.google.protobuf.ByteString
        getExtraBytes() {
      java.lang.Object ref = extra_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATE_DT_FIELD_NUMBER = 8;
    private long updateDt_;
    /**
     * <code>int64 update_dt = 8;</code>
     */
    public long getUpdateDt() {
      return updateDt_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTargetIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, targetId_);
      }
      if (line_ != 0) {
        output.writeInt32(2, line_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getPortraitBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, portrait_);
      }
      if (!getOwnerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, owner_);
      }
      if (type_ != win.liyufan.im.proto.GroupOuterClass.GroupType.GroupType_Normal.getNumber()) {
        output.writeEnum(6, type_);
      }
      if (!getExtraBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, extra_);
      }
      if (updateDt_ != 0L) {
        output.writeInt64(8, updateDt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTargetIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, targetId_);
      }
      if (line_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, line_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getPortraitBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, portrait_);
      }
      if (!getOwnerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, owner_);
      }
      if (type_ != win.liyufan.im.proto.GroupOuterClass.GroupType.GroupType_Normal.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_);
      }
      if (!getExtraBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, extra_);
      }
      if (updateDt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, updateDt_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.GroupOuterClass.GroupInfo)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.GroupOuterClass.GroupInfo other = (win.liyufan.im.proto.GroupOuterClass.GroupInfo) obj;

      boolean result = true;
      result = result && getTargetId()
          .equals(other.getTargetId());
      result = result && (getLine()
          == other.getLine());
      result = result && getName()
          .equals(other.getName());
      result = result && getPortrait()
          .equals(other.getPortrait());
      result = result && getOwner()
          .equals(other.getOwner());
      result = result && type_ == other.type_;
      result = result && getExtra()
          .equals(other.getExtra());
      result = result && (getUpdateDt()
          == other.getUpdateDt());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TARGET_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTargetId().hashCode();
      hash = (37 * hash) + LINE_FIELD_NUMBER;
      hash = (53 * hash) + getLine();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PORTRAIT_FIELD_NUMBER;
      hash = (53 * hash) + getPortrait().hashCode();
      hash = (37 * hash) + OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getOwner().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + getExtra().hashCode();
      hash = (37 * hash) + UPDATE_DT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateDt());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.GroupOuterClass.GroupInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mars.stn.GroupInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mars.stn.GroupInfo)
        win.liyufan.im.proto.GroupOuterClass.GroupInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.GroupOuterClass.internal_static_mars_stn_GroupInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.GroupOuterClass.internal_static_mars_stn_GroupInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.GroupOuterClass.GroupInfo.class, win.liyufan.im.proto.GroupOuterClass.GroupInfo.Builder.class);
      }

      // Construct using win.liyufan.im.proto.GroupOuterClass.GroupInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        targetId_ = "";

        line_ = 0;

        name_ = "";

        portrait_ = "";

        owner_ = "";

        type_ = 0;

        extra_ = "";

        updateDt_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.GroupOuterClass.internal_static_mars_stn_GroupInfo_descriptor;
      }

      public win.liyufan.im.proto.GroupOuterClass.GroupInfo getDefaultInstanceForType() {
        return win.liyufan.im.proto.GroupOuterClass.GroupInfo.getDefaultInstance();
      }

      public win.liyufan.im.proto.GroupOuterClass.GroupInfo build() {
        win.liyufan.im.proto.GroupOuterClass.GroupInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.GroupOuterClass.GroupInfo buildPartial() {
        win.liyufan.im.proto.GroupOuterClass.GroupInfo result = new win.liyufan.im.proto.GroupOuterClass.GroupInfo(this);
        result.targetId_ = targetId_;
        result.line_ = line_;
        result.name_ = name_;
        result.portrait_ = portrait_;
        result.owner_ = owner_;
        result.type_ = type_;
        result.extra_ = extra_;
        result.updateDt_ = updateDt_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.GroupOuterClass.GroupInfo) {
          return mergeFrom((win.liyufan.im.proto.GroupOuterClass.GroupInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.GroupOuterClass.GroupInfo other) {
        if (other == win.liyufan.im.proto.GroupOuterClass.GroupInfo.getDefaultInstance()) return this;
        if (!other.getTargetId().isEmpty()) {
          targetId_ = other.targetId_;
          onChanged();
        }
        if (other.getLine() != 0) {
          setLine(other.getLine());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getPortrait().isEmpty()) {
          portrait_ = other.portrait_;
          onChanged();
        }
        if (!other.getOwner().isEmpty()) {
          owner_ = other.owner_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getExtra().isEmpty()) {
          extra_ = other.extra_;
          onChanged();
        }
        if (other.getUpdateDt() != 0L) {
          setUpdateDt(other.getUpdateDt());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.GroupOuterClass.GroupInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.GroupOuterClass.GroupInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object targetId_ = "";
      /**
       * <code>string target_id = 1;</code>
       */
      public java.lang.String getTargetId() {
        java.lang.Object ref = targetId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          targetId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string target_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTargetIdBytes() {
        java.lang.Object ref = targetId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string target_id = 1;</code>
       */
      public Builder setTargetId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        targetId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string target_id = 1;</code>
       */
      public Builder clearTargetId() {
        
        targetId_ = getDefaultInstance().getTargetId();
        onChanged();
        return this;
      }
      /**
       * <code>string target_id = 1;</code>
       */
      public Builder setTargetIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        targetId_ = value;
        onChanged();
        return this;
      }

      private int line_ ;
      /**
       * <code>int32 line = 2;</code>
       */
      public int getLine() {
        return line_;
      }
      /**
       * <code>int32 line = 2;</code>
       */
      public Builder setLine(int value) {
        
        line_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 line = 2;</code>
       */
      public Builder clearLine() {
        
        line_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object portrait_ = "";
      /**
       * <code>string portrait = 4;</code>
       */
      public java.lang.String getPortrait() {
        java.lang.Object ref = portrait_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          portrait_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string portrait = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPortraitBytes() {
        java.lang.Object ref = portrait_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          portrait_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string portrait = 4;</code>
       */
      public Builder setPortrait(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        portrait_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string portrait = 4;</code>
       */
      public Builder clearPortrait() {
        
        portrait_ = getDefaultInstance().getPortrait();
        onChanged();
        return this;
      }
      /**
       * <code>string portrait = 4;</code>
       */
      public Builder setPortraitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        portrait_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>string owner = 5;</code>
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          owner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string owner = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string owner = 5;</code>
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 5;</code>
       */
      public Builder clearOwner() {
        
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string owner = 5;</code>
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        owner_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.mars.stn.GroupType type = 6;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.mars.stn.GroupType type = 6;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.mars.stn.GroupType type = 6;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.GroupType getType() {
        win.liyufan.im.proto.GroupOuterClass.GroupType result = win.liyufan.im.proto.GroupOuterClass.GroupType.valueOf(type_);
        return result == null ? win.liyufan.im.proto.GroupOuterClass.GroupType.UNRECOGNIZED : result;
      }
      /**
       * <code>.mars.stn.GroupType type = 6;</code>
       */
      public Builder setType(win.liyufan.im.proto.GroupOuterClass.GroupType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.mars.stn.GroupType type = 6;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object extra_ = "";
      /**
       * <code>string extra = 7;</code>
       */
      public java.lang.String getExtra() {
        java.lang.Object ref = extra_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          extra_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string extra = 7;</code>
       */
      public com.google.protobuf.ByteString
          getExtraBytes() {
        java.lang.Object ref = extra_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extra_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extra = 7;</code>
       */
      public Builder setExtra(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extra_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 7;</code>
       */
      public Builder clearExtra() {
        
        extra_ = getDefaultInstance().getExtra();
        onChanged();
        return this;
      }
      /**
       * <code>string extra = 7;</code>
       */
      public Builder setExtraBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extra_ = value;
        onChanged();
        return this;
      }

      private long updateDt_ ;
      /**
       * <code>int64 update_dt = 8;</code>
       */
      public long getUpdateDt() {
        return updateDt_;
      }
      /**
       * <code>int64 update_dt = 8;</code>
       */
      public Builder setUpdateDt(long value) {
        
        updateDt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 update_dt = 8;</code>
       */
      public Builder clearUpdateDt() {
        
        updateDt_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mars.stn.GroupInfo)
    }

    // @@protoc_insertion_point(class_scope:mars.stn.GroupInfo)
    private static final win.liyufan.im.proto.GroupOuterClass.GroupInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.GroupOuterClass.GroupInfo();
    }

    public static win.liyufan.im.proto.GroupOuterClass.GroupInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GroupInfo>
        PARSER = new com.google.protobuf.AbstractParser<GroupInfo>() {
      public GroupInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GroupInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GroupInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GroupInfo> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.GroupOuterClass.GroupInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mars.stn.Group)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.mars.stn.GroupInfo group_info = 1;</code>
     */
    boolean hasGroupInfo();
    /**
     * <code>.mars.stn.GroupInfo group_info = 1;</code>
     */
    win.liyufan.im.proto.GroupOuterClass.GroupInfo getGroupInfo();
    /**
     * <code>.mars.stn.GroupInfo group_info = 1;</code>
     */
    win.liyufan.im.proto.GroupOuterClass.GroupInfoOrBuilder getGroupInfoOrBuilder();

    /**
     * <code>repeated string members = 2;</code>
     */
    java.util.List<java.lang.String>
        getMembersList();
    /**
     * <code>repeated string members = 2;</code>
     */
    int getMembersCount();
    /**
     * <code>repeated string members = 2;</code>
     */
    java.lang.String getMembers(int index);
    /**
     * <code>repeated string members = 2;</code>
     */
    com.google.protobuf.ByteString
        getMembersBytes(int index);
  }
  /**
   * Protobuf type {@code mars.stn.Group}
   */
  public  static final class Group extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mars.stn.Group)
      GroupOrBuilder {
    // Use Group.newBuilder() to construct.
    private Group(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Group() {
      members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Group(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              win.liyufan.im.proto.GroupOuterClass.GroupInfo.Builder subBuilder = null;
              if (groupInfo_ != null) {
                subBuilder = groupInfo_.toBuilder();
              }
              groupInfo_ = input.readMessage(win.liyufan.im.proto.GroupOuterClass.GroupInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(groupInfo_);
                groupInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                members_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              members_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          members_ = members_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.GroupOuterClass.internal_static_mars_stn_Group_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.GroupOuterClass.internal_static_mars_stn_Group_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.GroupOuterClass.Group.class, win.liyufan.im.proto.GroupOuterClass.Group.Builder.class);
    }

    private int bitField0_;
    public static final int GROUP_INFO_FIELD_NUMBER = 1;
    private win.liyufan.im.proto.GroupOuterClass.GroupInfo groupInfo_;
    /**
     * <code>.mars.stn.GroupInfo group_info = 1;</code>
     */
    public boolean hasGroupInfo() {
      return groupInfo_ != null;
    }
    /**
     * <code>.mars.stn.GroupInfo group_info = 1;</code>
     */
    public win.liyufan.im.proto.GroupOuterClass.GroupInfo getGroupInfo() {
      return groupInfo_ == null ? win.liyufan.im.proto.GroupOuterClass.GroupInfo.getDefaultInstance() : groupInfo_;
    }
    /**
     * <code>.mars.stn.GroupInfo group_info = 1;</code>
     */
    public win.liyufan.im.proto.GroupOuterClass.GroupInfoOrBuilder getGroupInfoOrBuilder() {
      return getGroupInfo();
    }

    public static final int MEMBERS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList members_;
    /**
     * <code>repeated string members = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMembersList() {
      return members_;
    }
    /**
     * <code>repeated string members = 2;</code>
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated string members = 2;</code>
     */
    public java.lang.String getMembers(int index) {
      return members_.get(index);
    }
    /**
     * <code>repeated string members = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMembersBytes(int index) {
      return members_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (groupInfo_ != null) {
        output.writeMessage(1, getGroupInfo());
      }
      for (int i = 0; i < members_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, members_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (groupInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGroupInfo());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < members_.size(); i++) {
          dataSize += computeStringSizeNoTag(members_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMembersList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.GroupOuterClass.Group)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.GroupOuterClass.Group other = (win.liyufan.im.proto.GroupOuterClass.Group) obj;

      boolean result = true;
      result = result && (hasGroupInfo() == other.hasGroupInfo());
      if (hasGroupInfo()) {
        result = result && getGroupInfo()
            .equals(other.getGroupInfo());
      }
      result = result && getMembersList()
          .equals(other.getMembersList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGroupInfo()) {
        hash = (37 * hash) + GROUP_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getGroupInfo().hashCode();
      }
      if (getMembersCount() > 0) {
        hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getMembersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.GroupOuterClass.Group parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.GroupOuterClass.Group parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.GroupOuterClass.Group parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.GroupOuterClass.Group parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.GroupOuterClass.Group parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.GroupOuterClass.Group parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.GroupOuterClass.Group parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.GroupOuterClass.Group parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.GroupOuterClass.Group parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.GroupOuterClass.Group parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.GroupOuterClass.Group parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.GroupOuterClass.Group parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.GroupOuterClass.Group prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mars.stn.Group}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mars.stn.Group)
        win.liyufan.im.proto.GroupOuterClass.GroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.GroupOuterClass.internal_static_mars_stn_Group_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.GroupOuterClass.internal_static_mars_stn_Group_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.GroupOuterClass.Group.class, win.liyufan.im.proto.GroupOuterClass.Group.Builder.class);
      }

      // Construct using win.liyufan.im.proto.GroupOuterClass.Group.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (groupInfoBuilder_ == null) {
          groupInfo_ = null;
        } else {
          groupInfo_ = null;
          groupInfoBuilder_ = null;
        }
        members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.GroupOuterClass.internal_static_mars_stn_Group_descriptor;
      }

      public win.liyufan.im.proto.GroupOuterClass.Group getDefaultInstanceForType() {
        return win.liyufan.im.proto.GroupOuterClass.Group.getDefaultInstance();
      }

      public win.liyufan.im.proto.GroupOuterClass.Group build() {
        win.liyufan.im.proto.GroupOuterClass.Group result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.GroupOuterClass.Group buildPartial() {
        win.liyufan.im.proto.GroupOuterClass.Group result = new win.liyufan.im.proto.GroupOuterClass.Group(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (groupInfoBuilder_ == null) {
          result.groupInfo_ = groupInfo_;
        } else {
          result.groupInfo_ = groupInfoBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          members_ = members_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.members_ = members_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.GroupOuterClass.Group) {
          return mergeFrom((win.liyufan.im.proto.GroupOuterClass.Group)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.GroupOuterClass.Group other) {
        if (other == win.liyufan.im.proto.GroupOuterClass.Group.getDefaultInstance()) return this;
        if (other.hasGroupInfo()) {
          mergeGroupInfo(other.getGroupInfo());
        }
        if (!other.members_.isEmpty()) {
          if (members_.isEmpty()) {
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMembersIsMutable();
            members_.addAll(other.members_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.GroupOuterClass.Group parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.GroupOuterClass.Group) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private win.liyufan.im.proto.GroupOuterClass.GroupInfo groupInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.GroupOuterClass.GroupInfo, win.liyufan.im.proto.GroupOuterClass.GroupInfo.Builder, win.liyufan.im.proto.GroupOuterClass.GroupInfoOrBuilder> groupInfoBuilder_;
      /**
       * <code>.mars.stn.GroupInfo group_info = 1;</code>
       */
      public boolean hasGroupInfo() {
        return groupInfoBuilder_ != null || groupInfo_ != null;
      }
      /**
       * <code>.mars.stn.GroupInfo group_info = 1;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.GroupInfo getGroupInfo() {
        if (groupInfoBuilder_ == null) {
          return groupInfo_ == null ? win.liyufan.im.proto.GroupOuterClass.GroupInfo.getDefaultInstance() : groupInfo_;
        } else {
          return groupInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.mars.stn.GroupInfo group_info = 1;</code>
       */
      public Builder setGroupInfo(win.liyufan.im.proto.GroupOuterClass.GroupInfo value) {
        if (groupInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          groupInfo_ = value;
          onChanged();
        } else {
          groupInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.mars.stn.GroupInfo group_info = 1;</code>
       */
      public Builder setGroupInfo(
          win.liyufan.im.proto.GroupOuterClass.GroupInfo.Builder builderForValue) {
        if (groupInfoBuilder_ == null) {
          groupInfo_ = builderForValue.build();
          onChanged();
        } else {
          groupInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.mars.stn.GroupInfo group_info = 1;</code>
       */
      public Builder mergeGroupInfo(win.liyufan.im.proto.GroupOuterClass.GroupInfo value) {
        if (groupInfoBuilder_ == null) {
          if (groupInfo_ != null) {
            groupInfo_ =
              win.liyufan.im.proto.GroupOuterClass.GroupInfo.newBuilder(groupInfo_).mergeFrom(value).buildPartial();
          } else {
            groupInfo_ = value;
          }
          onChanged();
        } else {
          groupInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.mars.stn.GroupInfo group_info = 1;</code>
       */
      public Builder clearGroupInfo() {
        if (groupInfoBuilder_ == null) {
          groupInfo_ = null;
          onChanged();
        } else {
          groupInfo_ = null;
          groupInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.mars.stn.GroupInfo group_info = 1;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.GroupInfo.Builder getGroupInfoBuilder() {
        
        onChanged();
        return getGroupInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.mars.stn.GroupInfo group_info = 1;</code>
       */
      public win.liyufan.im.proto.GroupOuterClass.GroupInfoOrBuilder getGroupInfoOrBuilder() {
        if (groupInfoBuilder_ != null) {
          return groupInfoBuilder_.getMessageOrBuilder();
        } else {
          return groupInfo_ == null ?
              win.liyufan.im.proto.GroupOuterClass.GroupInfo.getDefaultInstance() : groupInfo_;
        }
      }
      /**
       * <code>.mars.stn.GroupInfo group_info = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.GroupOuterClass.GroupInfo, win.liyufan.im.proto.GroupOuterClass.GroupInfo.Builder, win.liyufan.im.proto.GroupOuterClass.GroupInfoOrBuilder> 
          getGroupInfoFieldBuilder() {
        if (groupInfoBuilder_ == null) {
          groupInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              win.liyufan.im.proto.GroupOuterClass.GroupInfo, win.liyufan.im.proto.GroupOuterClass.GroupInfo.Builder, win.liyufan.im.proto.GroupOuterClass.GroupInfoOrBuilder>(
                  getGroupInfo(),
                  getParentForChildren(),
                  isClean());
          groupInfo_ = null;
        }
        return groupInfoBuilder_;
      }

      private com.google.protobuf.LazyStringList members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMembersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          members_ = new com.google.protobuf.LazyStringArrayList(members_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string members = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getMembersList() {
        return members_.getUnmodifiableView();
      }
      /**
       * <code>repeated string members = 2;</code>
       */
      public int getMembersCount() {
        return members_.size();
      }
      /**
       * <code>repeated string members = 2;</code>
       */
      public java.lang.String getMembers(int index) {
        return members_.get(index);
      }
      /**
       * <code>repeated string members = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMembersBytes(int index) {
        return members_.getByteString(index);
      }
      /**
       * <code>repeated string members = 2;</code>
       */
      public Builder setMembers(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersIsMutable();
        members_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 2;</code>
       */
      public Builder addMembers(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMembersIsMutable();
        members_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 2;</code>
       */
      public Builder addAllMembers(
          java.lang.Iterable<java.lang.String> values) {
        ensureMembersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, members_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 2;</code>
       */
      public Builder clearMembers() {
        members_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string members = 2;</code>
       */
      public Builder addMembersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMembersIsMutable();
        members_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mars.stn.Group)
    }

    // @@protoc_insertion_point(class_scope:mars.stn.Group)
    private static final win.liyufan.im.proto.GroupOuterClass.Group DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.GroupOuterClass.Group();
    }

    public static win.liyufan.im.proto.GroupOuterClass.Group getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Group>
        PARSER = new com.google.protobuf.AbstractParser<Group>() {
      public Group parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Group(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Group> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Group> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.GroupOuterClass.Group getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mars_stn_GroupInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mars_stn_GroupInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mars_stn_Group_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mars_stn_Group_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013group.proto\022\010mars.stn\"\240\001\n\tGroupInfo\022\021\n" +
      "\ttarget_id\030\001 \001(\t\022\014\n\004line\030\002 \001(\005\022\014\n\004name\030\003" +
      " \001(\t\022\020\n\010portrait\030\004 \001(\t\022\r\n\005owner\030\005 \001(\t\022!\n" +
      "\004type\030\006 \001(\0162\023.mars.stn.GroupType\022\r\n\005extr" +
      "a\030\007 \001(\t\022\021\n\tupdate_dt\030\010 \001(\003\"A\n\005Group\022\'\n\ng" +
      "roup_info\030\001 \001(\0132\023.mars.stn.GroupInfo\022\017\n\007" +
      "members\030\002 \003(\t*O\n\tGroupType\022\024\n\020GroupType_" +
      "Normal\020\000\022\022\n\016GroupType_Free\020\001\022\030\n\024GroupTyp" +
      "e_Restricted\020\002B\'\n\024win.liyufan.im.protoB\017" +
      "GroupOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mars_stn_GroupInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mars_stn_GroupInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mars_stn_GroupInfo_descriptor,
        new java.lang.String[] { "TargetId", "Line", "Name", "Portrait", "Owner", "Type", "Extra", "UpdateDt", });
    internal_static_mars_stn_Group_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mars_stn_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mars_stn_Group_descriptor,
        new java.lang.String[] { "GroupInfo", "Members", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
