// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: handle_friends_request.proto

package win.liyufan.im.proto;

public final class HandleFriendRequestOuterClass {
  private HandleFriendRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HandleFriendRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mars.stn.HandleFriendRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string target_uid = 1;</code>
     */
    java.lang.String getTargetUid();
    /**
     * <code>string target_uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getTargetUidBytes();

    /**
     * <code>int32 status = 2;</code>
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code mars.stn.HandleFriendRequest}
   */
  public  static final class HandleFriendRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mars.stn.HandleFriendRequest)
      HandleFriendRequestOrBuilder {
    // Use HandleFriendRequest.newBuilder() to construct.
    private HandleFriendRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HandleFriendRequest() {
      targetUid_ = "";
      status_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HandleFriendRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              targetUid_ = s;
              break;
            }
            case 16: {

              status_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.HandleFriendRequestOuterClass.internal_static_mars_stn_HandleFriendRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.HandleFriendRequestOuterClass.internal_static_mars_stn_HandleFriendRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest.class, win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest.Builder.class);
    }

    public static final int TARGET_UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object targetUid_;
    /**
     * <code>string target_uid = 1;</code>
     */
    public java.lang.String getTargetUid() {
      java.lang.Object ref = targetUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        targetUid_ = s;
        return s;
      }
    }
    /**
     * <code>string target_uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTargetUidBytes() {
      java.lang.Object ref = targetUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>int32 status = 2;</code>
     */
    public int getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTargetUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, targetUid_);
      }
      if (status_ != 0) {
        output.writeInt32(2, status_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTargetUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, targetUid_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest other = (win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest) obj;

      boolean result = true;
      result = result && getTargetUid()
          .equals(other.getTargetUid());
      result = result && (getStatus()
          == other.getStatus());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TARGET_UID_FIELD_NUMBER;
      hash = (53 * hash) + getTargetUid().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mars.stn.HandleFriendRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mars.stn.HandleFriendRequest)
        win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.HandleFriendRequestOuterClass.internal_static_mars_stn_HandleFriendRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.HandleFriendRequestOuterClass.internal_static_mars_stn_HandleFriendRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest.class, win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest.Builder.class);
      }

      // Construct using win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        targetUid_ = "";

        status_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.HandleFriendRequestOuterClass.internal_static_mars_stn_HandleFriendRequest_descriptor;
      }

      public win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest getDefaultInstanceForType() {
        return win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest.getDefaultInstance();
      }

      public win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest build() {
        win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest buildPartial() {
        win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest result = new win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest(this);
        result.targetUid_ = targetUid_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest) {
          return mergeFrom((win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest other) {
        if (other == win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest.getDefaultInstance()) return this;
        if (!other.getTargetUid().isEmpty()) {
          targetUid_ = other.targetUid_;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object targetUid_ = "";
      /**
       * <code>string target_uid = 1;</code>
       */
      public java.lang.String getTargetUid() {
        java.lang.Object ref = targetUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          targetUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string target_uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTargetUidBytes() {
        java.lang.Object ref = targetUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string target_uid = 1;</code>
       */
      public Builder setTargetUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        targetUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string target_uid = 1;</code>
       */
      public Builder clearTargetUid() {
        
        targetUid_ = getDefaultInstance().getTargetUid();
        onChanged();
        return this;
      }
      /**
       * <code>string target_uid = 1;</code>
       */
      public Builder setTargetUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        targetUid_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 2;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 2;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mars.stn.HandleFriendRequest)
    }

    // @@protoc_insertion_point(class_scope:mars.stn.HandleFriendRequest)
    private static final win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest();
    }

    public static win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HandleFriendRequest>
        PARSER = new com.google.protobuf.AbstractParser<HandleFriendRequest>() {
      public HandleFriendRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HandleFriendRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HandleFriendRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HandleFriendRequest> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.HandleFriendRequestOuterClass.HandleFriendRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mars_stn_HandleFriendRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mars_stn_HandleFriendRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034handle_friends_request.proto\022\010mars.stn" +
      "\"9\n\023HandleFriendRequest\022\022\n\ntarget_uid\030\001 " +
      "\001(\t\022\016\n\006status\030\002 \001(\005B5\n\024win.liyufan.im.pr" +
      "otoB\035HandleFriendRequestOuterClassb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mars_stn_HandleFriendRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mars_stn_HandleFriendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mars_stn_HandleFriendRequest_descriptor,
        new java.lang.String[] { "TargetUid", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
