// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modify_my_info_request.proto

package win.liyufan.im.proto;

public final class ModifyMyInfoOuterClass {
  private ModifyMyInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InfoEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mars.stn.InfoEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 type = 1;</code>
     */
    int getType();

    /**
     * <code>string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code mars.stn.InfoEntry}
   */
  public  static final class InfoEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mars.stn.InfoEntry)
      InfoEntryOrBuilder {
    // Use InfoEntry.newBuilder() to construct.
    private InfoEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InfoEntry() {
      type_ = 0;
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InfoEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              type_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.ModifyMyInfoOuterClass.internal_static_mars_stn_InfoEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.ModifyMyInfoOuterClass.internal_static_mars_stn_InfoEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.class, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != 0) {
        output.writeInt32(1, type_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry other = (win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry) obj;

      boolean result = true;
      result = result && (getType()
          == other.getType());
      result = result && getValue()
          .equals(other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mars.stn.InfoEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mars.stn.InfoEntry)
        win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.ModifyMyInfoOuterClass.internal_static_mars_stn_InfoEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.ModifyMyInfoOuterClass.internal_static_mars_stn_InfoEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.class, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder.class);
      }

      // Construct using win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        value_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.ModifyMyInfoOuterClass.internal_static_mars_stn_InfoEntry_descriptor;
      }

      public win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry getDefaultInstanceForType() {
        return win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.getDefaultInstance();
      }

      public win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry build() {
        win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry buildPartial() {
        win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry result = new win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry(this);
        result.type_ = type_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry) {
          return mergeFrom((win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry other) {
        if (other == win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.getDefaultInstance()) return this;
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mars.stn.InfoEntry)
    }

    // @@protoc_insertion_point(class_scope:mars.stn.InfoEntry)
    private static final win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry();
    }

    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InfoEntry>
        PARSER = new com.google.protobuf.AbstractParser<InfoEntry>() {
      public InfoEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InfoEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InfoEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InfoEntry> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ModifyMyInfoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mars.stn.ModifyMyInfoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
     */
    java.util.List<win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry> 
        getEntryList();
    /**
     * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
     */
    win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry getEntry(int index);
    /**
     * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
     */
    int getEntryCount();
    /**
     * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
     */
    java.util.List<? extends win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntryOrBuilder> 
        getEntryOrBuilderList();
    /**
     * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
     */
    win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntryOrBuilder getEntryOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code mars.stn.ModifyMyInfoRequest}
   */
  public  static final class ModifyMyInfoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mars.stn.ModifyMyInfoRequest)
      ModifyMyInfoRequestOrBuilder {
    // Use ModifyMyInfoRequest.newBuilder() to construct.
    private ModifyMyInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ModifyMyInfoRequest() {
      entry_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ModifyMyInfoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                entry_ = new java.util.ArrayList<win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              entry_.add(
                  input.readMessage(win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = java.util.Collections.unmodifiableList(entry_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.ModifyMyInfoOuterClass.internal_static_mars_stn_ModifyMyInfoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.ModifyMyInfoOuterClass.internal_static_mars_stn_ModifyMyInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest.class, win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest.Builder.class);
    }

    public static final int ENTRY_FIELD_NUMBER = 1;
    private java.util.List<win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry> entry_;
    /**
     * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
     */
    public java.util.List<win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry> getEntryList() {
      return entry_;
    }
    /**
     * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
     */
    public java.util.List<? extends win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntryOrBuilder> 
        getEntryOrBuilderList() {
      return entry_;
    }
    /**
     * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
     */
    public int getEntryCount() {
      return entry_.size();
    }
    /**
     * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
     */
    public win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry getEntry(int index) {
      return entry_.get(index);
    }
    /**
     * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
     */
    public win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntryOrBuilder getEntryOrBuilder(
        int index) {
      return entry_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < entry_.size(); i++) {
        output.writeMessage(1, entry_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entry_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest other = (win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest) obj;

      boolean result = true;
      result = result && getEntryList()
          .equals(other.getEntryList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEntryCount() > 0) {
        hash = (37 * hash) + ENTRY_FIELD_NUMBER;
        hash = (53 * hash) + getEntryList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mars.stn.ModifyMyInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mars.stn.ModifyMyInfoRequest)
        win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.ModifyMyInfoOuterClass.internal_static_mars_stn_ModifyMyInfoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.ModifyMyInfoOuterClass.internal_static_mars_stn_ModifyMyInfoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest.class, win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest.Builder.class);
      }

      // Construct using win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEntryFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entryBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.ModifyMyInfoOuterClass.internal_static_mars_stn_ModifyMyInfoRequest_descriptor;
      }

      public win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest getDefaultInstanceForType() {
        return win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest.getDefaultInstance();
      }

      public win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest build() {
        win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest buildPartial() {
        win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest result = new win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest(this);
        int from_bitField0_ = bitField0_;
        if (entryBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            entry_ = java.util.Collections.unmodifiableList(entry_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entry_ = entry_;
        } else {
          result.entry_ = entryBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest) {
          return mergeFrom((win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest other) {
        if (other == win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest.getDefaultInstance()) return this;
        if (entryBuilder_ == null) {
          if (!other.entry_.isEmpty()) {
            if (entry_.isEmpty()) {
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntryIsMutable();
              entry_.addAll(other.entry_);
            }
            onChanged();
          }
        } else {
          if (!other.entry_.isEmpty()) {
            if (entryBuilder_.isEmpty()) {
              entryBuilder_.dispose();
              entryBuilder_ = null;
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entryBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEntryFieldBuilder() : null;
            } else {
              entryBuilder_.addAllMessages(other.entry_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry> entry_ =
        java.util.Collections.emptyList();
      private void ensureEntryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          entry_ = new java.util.ArrayList<win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry>(entry_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntryOrBuilder> entryBuilder_;

      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public java.util.List<win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry> getEntryList() {
        if (entryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entry_);
        } else {
          return entryBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public int getEntryCount() {
        if (entryBuilder_ == null) {
          return entry_.size();
        } else {
          return entryBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry getEntry(int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);
        } else {
          return entryBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public Builder setEntry(
          int index, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.set(index, value);
          onChanged();
        } else {
          entryBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public Builder setEntry(
          int index, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.set(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public Builder addEntry(win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(value);
          onChanged();
        } else {
          entryBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public Builder addEntry(
          int index, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(index, value);
          onChanged();
        } else {
          entryBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public Builder addEntry(
          win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public Builder addEntry(
          int index, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public Builder addAllEntry(
          java.lang.Iterable<? extends win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry> values) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, entry_);
          onChanged();
        } else {
          entryBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public Builder clearEntry() {
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entryBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public Builder removeEntry(int index) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.remove(index);
          onChanged();
        } else {
          entryBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder getEntryBuilder(
          int index) {
        return getEntryFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntryOrBuilder getEntryOrBuilder(
          int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);  } else {
          return entryBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public java.util.List<? extends win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntryOrBuilder> 
           getEntryOrBuilderList() {
        if (entryBuilder_ != null) {
          return entryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entry_);
        }
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder addEntryBuilder() {
        return getEntryFieldBuilder().addBuilder(
            win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder addEntryBuilder(
          int index) {
        return getEntryFieldBuilder().addBuilder(
            index, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .mars.stn.InfoEntry entry = 1;</code>
       */
      public java.util.List<win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder> 
           getEntryBuilderList() {
        return getEntryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntryOrBuilder> 
          getEntryFieldBuilder() {
        if (entryBuilder_ == null) {
          entryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntry.Builder, win.liyufan.im.proto.ModifyMyInfoOuterClass.InfoEntryOrBuilder>(
                  entry_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          entry_ = null;
        }
        return entryBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mars.stn.ModifyMyInfoRequest)
    }

    // @@protoc_insertion_point(class_scope:mars.stn.ModifyMyInfoRequest)
    private static final win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest();
    }

    public static win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ModifyMyInfoRequest>
        PARSER = new com.google.protobuf.AbstractParser<ModifyMyInfoRequest>() {
      public ModifyMyInfoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ModifyMyInfoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ModifyMyInfoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ModifyMyInfoRequest> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.ModifyMyInfoOuterClass.ModifyMyInfoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mars_stn_InfoEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mars_stn_InfoEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mars_stn_ModifyMyInfoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mars_stn_ModifyMyInfoRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034modify_my_info_request.proto\022\010mars.stn" +
      "\"(\n\tInfoEntry\022\014\n\004type\030\001 \001(\005\022\r\n\005value\030\002 \001" +
      "(\t\"9\n\023ModifyMyInfoRequest\022\"\n\005entry\030\001 \003(\013" +
      "2\023.mars.stn.InfoEntryB.\n\024win.liyufan.im." +
      "protoB\026ModifyMyInfoOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mars_stn_InfoEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mars_stn_InfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mars_stn_InfoEntry_descriptor,
        new java.lang.String[] { "Type", "Value", });
    internal_static_mars_stn_ModifyMyInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mars_stn_ModifyMyInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mars_stn_ModifyMyInfoRequest_descriptor,
        new java.lang.String[] { "Entry", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
