// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pull_user_response.proto

package win.liyufan.im.proto;

public final class PullUserResultOuterClass {
  private PullUserResultOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code mars.stn.UserResultCode}
   */
  public enum UserResultCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Success = 0;</code>
     */
    Success(0),
    /**
     * <code>NotFound = 1;</code>
     */
    NotFound(1),
    /**
     * <code>NotModified = 2;</code>
     */
    NotModified(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Success = 0;</code>
     */
    public static final int Success_VALUE = 0;
    /**
     * <code>NotFound = 1;</code>
     */
    public static final int NotFound_VALUE = 1;
    /**
     * <code>NotModified = 2;</code>
     */
    public static final int NotModified_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserResultCode valueOf(int value) {
      return forNumber(value);
    }

    public static UserResultCode forNumber(int value) {
      switch (value) {
        case 0: return Success;
        case 1: return NotFound;
        case 2: return NotModified;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserResultCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserResultCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserResultCode>() {
            public UserResultCode findValueByNumber(int number) {
              return UserResultCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return win.liyufan.im.proto.PullUserResultOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final UserResultCode[] VALUES = values();

    public static UserResultCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserResultCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:mars.stn.UserResultCode)
  }

  public interface UserResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mars.stn.UserResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.mars.stn.User user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>.mars.stn.User user = 1;</code>
     */
    win.liyufan.im.proto.UserOuterClass.User getUser();
    /**
     * <code>.mars.stn.User user = 1;</code>
     */
    win.liyufan.im.proto.UserOuterClass.UserOrBuilder getUserOrBuilder();

    /**
     * <code>.mars.stn.UserResultCode code = 2;</code>
     */
    int getCodeValue();
    /**
     * <code>.mars.stn.UserResultCode code = 2;</code>
     */
    win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode getCode();
  }
  /**
   * Protobuf type {@code mars.stn.UserResult}
   */
  public  static final class UserResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mars.stn.UserResult)
      UserResultOrBuilder {
    // Use UserResult.newBuilder() to construct.
    private UserResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserResult() {
      code_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              win.liyufan.im.proto.UserOuterClass.User.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(win.liyufan.im.proto.UserOuterClass.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.PullUserResultOuterClass.internal_static_mars_stn_UserResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.PullUserResultOuterClass.internal_static_mars_stn_UserResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.PullUserResultOuterClass.UserResult.class, win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private win.liyufan.im.proto.UserOuterClass.User user_;
    /**
     * <code>.mars.stn.User user = 1;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.mars.stn.User user = 1;</code>
     */
    public win.liyufan.im.proto.UserOuterClass.User getUser() {
      return user_ == null ? win.liyufan.im.proto.UserOuterClass.User.getDefaultInstance() : user_;
    }
    /**
     * <code>.mars.stn.User user = 1;</code>
     */
    public win.liyufan.im.proto.UserOuterClass.UserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>.mars.stn.UserResultCode code = 2;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.mars.stn.UserResultCode code = 2;</code>
     */
    public win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode getCode() {
      win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode result = win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode.valueOf(code_);
      return result == null ? win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (user_ != null) {
        output.writeMessage(1, getUser());
      }
      if (code_ != win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode.Success.getNumber()) {
        output.writeEnum(2, code_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUser());
      }
      if (code_ != win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode.Success.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, code_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.PullUserResultOuterClass.UserResult)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.PullUserResultOuterClass.UserResult other = (win.liyufan.im.proto.PullUserResultOuterClass.UserResult) obj;

      boolean result = true;
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && code_ == other.code_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.PullUserResultOuterClass.UserResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mars.stn.UserResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mars.stn.UserResult)
        win.liyufan.im.proto.PullUserResultOuterClass.UserResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.PullUserResultOuterClass.internal_static_mars_stn_UserResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.PullUserResultOuterClass.internal_static_mars_stn_UserResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.PullUserResultOuterClass.UserResult.class, win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder.class);
      }

      // Construct using win.liyufan.im.proto.PullUserResultOuterClass.UserResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        code_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.PullUserResultOuterClass.internal_static_mars_stn_UserResult_descriptor;
      }

      public win.liyufan.im.proto.PullUserResultOuterClass.UserResult getDefaultInstanceForType() {
        return win.liyufan.im.proto.PullUserResultOuterClass.UserResult.getDefaultInstance();
      }

      public win.liyufan.im.proto.PullUserResultOuterClass.UserResult build() {
        win.liyufan.im.proto.PullUserResultOuterClass.UserResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.PullUserResultOuterClass.UserResult buildPartial() {
        win.liyufan.im.proto.PullUserResultOuterClass.UserResult result = new win.liyufan.im.proto.PullUserResultOuterClass.UserResult(this);
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        result.code_ = code_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.PullUserResultOuterClass.UserResult) {
          return mergeFrom((win.liyufan.im.proto.PullUserResultOuterClass.UserResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.PullUserResultOuterClass.UserResult other) {
        if (other == win.liyufan.im.proto.PullUserResultOuterClass.UserResult.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.PullUserResultOuterClass.UserResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.PullUserResultOuterClass.UserResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private win.liyufan.im.proto.UserOuterClass.User user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.UserOuterClass.User, win.liyufan.im.proto.UserOuterClass.User.Builder, win.liyufan.im.proto.UserOuterClass.UserOrBuilder> userBuilder_;
      /**
       * <code>.mars.stn.User user = 1;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.mars.stn.User user = 1;</code>
       */
      public win.liyufan.im.proto.UserOuterClass.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? win.liyufan.im.proto.UserOuterClass.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.mars.stn.User user = 1;</code>
       */
      public Builder setUser(win.liyufan.im.proto.UserOuterClass.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.mars.stn.User user = 1;</code>
       */
      public Builder setUser(
          win.liyufan.im.proto.UserOuterClass.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.mars.stn.User user = 1;</code>
       */
      public Builder mergeUser(win.liyufan.im.proto.UserOuterClass.User value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              win.liyufan.im.proto.UserOuterClass.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.mars.stn.User user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.mars.stn.User user = 1;</code>
       */
      public win.liyufan.im.proto.UserOuterClass.User.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.mars.stn.User user = 1;</code>
       */
      public win.liyufan.im.proto.UserOuterClass.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              win.liyufan.im.proto.UserOuterClass.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.mars.stn.User user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.UserOuterClass.User, win.liyufan.im.proto.UserOuterClass.User.Builder, win.liyufan.im.proto.UserOuterClass.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              win.liyufan.im.proto.UserOuterClass.User, win.liyufan.im.proto.UserOuterClass.User.Builder, win.liyufan.im.proto.UserOuterClass.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private int code_ = 0;
      /**
       * <code>.mars.stn.UserResultCode code = 2;</code>
       */
      public int getCodeValue() {
        return code_;
      }
      /**
       * <code>.mars.stn.UserResultCode code = 2;</code>
       */
      public Builder setCodeValue(int value) {
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.mars.stn.UserResultCode code = 2;</code>
       */
      public win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode getCode() {
        win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode result = win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode.valueOf(code_);
        return result == null ? win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.mars.stn.UserResultCode code = 2;</code>
       */
      public Builder setCode(win.liyufan.im.proto.PullUserResultOuterClass.UserResultCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.mars.stn.UserResultCode code = 2;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mars.stn.UserResult)
    }

    // @@protoc_insertion_point(class_scope:mars.stn.UserResult)
    private static final win.liyufan.im.proto.PullUserResultOuterClass.UserResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.PullUserResultOuterClass.UserResult();
    }

    public static win.liyufan.im.proto.PullUserResultOuterClass.UserResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserResult>
        PARSER = new com.google.protobuf.AbstractParser<UserResult>() {
      public UserResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserResult> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.PullUserResultOuterClass.UserResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PullUserResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mars.stn.PullUserResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .mars.stn.UserResult result = 1;</code>
     */
    java.util.List<win.liyufan.im.proto.PullUserResultOuterClass.UserResult> 
        getResultList();
    /**
     * <code>repeated .mars.stn.UserResult result = 1;</code>
     */
    win.liyufan.im.proto.PullUserResultOuterClass.UserResult getResult(int index);
    /**
     * <code>repeated .mars.stn.UserResult result = 1;</code>
     */
    int getResultCount();
    /**
     * <code>repeated .mars.stn.UserResult result = 1;</code>
     */
    java.util.List<? extends win.liyufan.im.proto.PullUserResultOuterClass.UserResultOrBuilder> 
        getResultOrBuilderList();
    /**
     * <code>repeated .mars.stn.UserResult result = 1;</code>
     */
    win.liyufan.im.proto.PullUserResultOuterClass.UserResultOrBuilder getResultOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code mars.stn.PullUserResult}
   */
  public  static final class PullUserResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mars.stn.PullUserResult)
      PullUserResultOrBuilder {
    // Use PullUserResult.newBuilder() to construct.
    private PullUserResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PullUserResult() {
      result_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PullUserResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                result_ = new java.util.ArrayList<win.liyufan.im.proto.PullUserResultOuterClass.UserResult>();
                mutable_bitField0_ |= 0x00000001;
              }
              result_.add(
                  input.readMessage(win.liyufan.im.proto.PullUserResultOuterClass.UserResult.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.PullUserResultOuterClass.internal_static_mars_stn_PullUserResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.PullUserResultOuterClass.internal_static_mars_stn_PullUserResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult.class, win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private java.util.List<win.liyufan.im.proto.PullUserResultOuterClass.UserResult> result_;
    /**
     * <code>repeated .mars.stn.UserResult result = 1;</code>
     */
    public java.util.List<win.liyufan.im.proto.PullUserResultOuterClass.UserResult> getResultList() {
      return result_;
    }
    /**
     * <code>repeated .mars.stn.UserResult result = 1;</code>
     */
    public java.util.List<? extends win.liyufan.im.proto.PullUserResultOuterClass.UserResultOrBuilder> 
        getResultOrBuilderList() {
      return result_;
    }
    /**
     * <code>repeated .mars.stn.UserResult result = 1;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated .mars.stn.UserResult result = 1;</code>
     */
    public win.liyufan.im.proto.PullUserResultOuterClass.UserResult getResult(int index) {
      return result_.get(index);
    }
    /**
     * <code>repeated .mars.stn.UserResult result = 1;</code>
     */
    public win.liyufan.im.proto.PullUserResultOuterClass.UserResultOrBuilder getResultOrBuilder(
        int index) {
      return result_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < result_.size(); i++) {
        output.writeMessage(1, result_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < result_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, result_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult other = (win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult) obj;

      boolean result = true;
      result = result && getResultList()
          .equals(other.getResultList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResultCount() > 0) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResultList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mars.stn.PullUserResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mars.stn.PullUserResult)
        win.liyufan.im.proto.PullUserResultOuterClass.PullUserResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.PullUserResultOuterClass.internal_static_mars_stn_PullUserResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.PullUserResultOuterClass.internal_static_mars_stn_PullUserResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult.class, win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult.Builder.class);
      }

      // Construct using win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resultBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.PullUserResultOuterClass.internal_static_mars_stn_PullUserResult_descriptor;
      }

      public win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult getDefaultInstanceForType() {
        return win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult.getDefaultInstance();
      }

      public win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult build() {
        win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult buildPartial() {
        win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult result = new win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult(this);
        int from_bitField0_ = bitField0_;
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            result_ = java.util.Collections.unmodifiableList(result_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult) {
          return mergeFrom((win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult other) {
        if (other == win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult.getDefaultInstance()) return this;
        if (resultBuilder_ == null) {
          if (!other.result_.isEmpty()) {
            if (result_.isEmpty()) {
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultIsMutable();
              result_.addAll(other.result_);
            }
            onChanged();
          }
        } else {
          if (!other.result_.isEmpty()) {
            if (resultBuilder_.isEmpty()) {
              resultBuilder_.dispose();
              resultBuilder_ = null;
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultFieldBuilder() : null;
            } else {
              resultBuilder_.addAllMessages(other.result_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<win.liyufan.im.proto.PullUserResultOuterClass.UserResult> result_ =
        java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = new java.util.ArrayList<win.liyufan.im.proto.PullUserResultOuterClass.UserResult>(result_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          win.liyufan.im.proto.PullUserResultOuterClass.UserResult, win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder, win.liyufan.im.proto.PullUserResultOuterClass.UserResultOrBuilder> resultBuilder_;

      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public java.util.List<win.liyufan.im.proto.PullUserResultOuterClass.UserResult> getResultList() {
        if (resultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(result_);
        } else {
          return resultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public int getResultCount() {
        if (resultBuilder_ == null) {
          return result_.size();
        } else {
          return resultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public win.liyufan.im.proto.PullUserResultOuterClass.UserResult getResult(int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);
        } else {
          return resultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public Builder setResult(
          int index, win.liyufan.im.proto.PullUserResultOuterClass.UserResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.set(index, value);
          onChanged();
        } else {
          resultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public Builder setResult(
          int index, win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public Builder addResult(win.liyufan.im.proto.PullUserResultOuterClass.UserResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(value);
          onChanged();
        } else {
          resultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public Builder addResult(
          int index, win.liyufan.im.proto.PullUserResultOuterClass.UserResult value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(index, value);
          onChanged();
        } else {
          resultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public Builder addResult(
          win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public Builder addResult(
          int index, win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends win.liyufan.im.proto.PullUserResultOuterClass.UserResult> values) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, result_);
          onChanged();
        } else {
          resultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public Builder removeResult(int index) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.remove(index);
          onChanged();
        } else {
          resultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder getResultBuilder(
          int index) {
        return getResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public win.liyufan.im.proto.PullUserResultOuterClass.UserResultOrBuilder getResultOrBuilder(
          int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);  } else {
          return resultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public java.util.List<? extends win.liyufan.im.proto.PullUserResultOuterClass.UserResultOrBuilder> 
           getResultOrBuilderList() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result_);
        }
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder addResultBuilder() {
        return getResultFieldBuilder().addBuilder(
            win.liyufan.im.proto.PullUserResultOuterClass.UserResult.getDefaultInstance());
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder addResultBuilder(
          int index) {
        return getResultFieldBuilder().addBuilder(
            index, win.liyufan.im.proto.PullUserResultOuterClass.UserResult.getDefaultInstance());
      }
      /**
       * <code>repeated .mars.stn.UserResult result = 1;</code>
       */
      public java.util.List<win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder> 
           getResultBuilderList() {
        return getResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          win.liyufan.im.proto.PullUserResultOuterClass.UserResult, win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder, win.liyufan.im.proto.PullUserResultOuterClass.UserResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              win.liyufan.im.proto.PullUserResultOuterClass.UserResult, win.liyufan.im.proto.PullUserResultOuterClass.UserResult.Builder, win.liyufan.im.proto.PullUserResultOuterClass.UserResultOrBuilder>(
                  result_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mars.stn.PullUserResult)
    }

    // @@protoc_insertion_point(class_scope:mars.stn.PullUserResult)
    private static final win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult();
    }

    public static win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PullUserResult>
        PARSER = new com.google.protobuf.AbstractParser<PullUserResult>() {
      public PullUserResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PullUserResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PullUserResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PullUserResult> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.PullUserResultOuterClass.PullUserResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mars_stn_UserResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mars_stn_UserResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mars_stn_PullUserResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mars_stn_PullUserResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030pull_user_response.proto\022\010mars.stn\032\nus" +
      "er.proto\"R\n\nUserResult\022\034\n\004user\030\001 \001(\0132\016.m" +
      "ars.stn.User\022&\n\004code\030\002 \001(\0162\030.mars.stn.Us" +
      "erResultCode\"6\n\016PullUserResult\022$\n\006result" +
      "\030\001 \003(\0132\024.mars.stn.UserResult*<\n\016UserResu" +
      "ltCode\022\013\n\007Success\020\000\022\014\n\010NotFound\020\001\022\017\n\013Not" +
      "Modified\020\002B0\n\024win.liyufan.im.protoB\030Pull" +
      "UserResultOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          win.liyufan.im.proto.UserOuterClass.getDescriptor(),
        }, assigner);
    internal_static_mars_stn_UserResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mars_stn_UserResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mars_stn_UserResult_descriptor,
        new java.lang.String[] { "User", "Code", });
    internal_static_mars_stn_PullUserResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mars_stn_PullUserResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mars_stn_PullUserResult_descriptor,
        new java.lang.String[] { "Result", });
    win.liyufan.im.proto.UserOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
