// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pull_user_request.proto

package win.liyufan.im.proto;

public final class PullUserRequestOuterClass {
  private PullUserRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mars.stn.UserRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>int64 update_dt = 2;</code>
     */
    long getUpdateDt();
  }
  /**
   * Protobuf type {@code mars.stn.UserRequest}
   */
  public  static final class UserRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mars.stn.UserRequest)
      UserRequestOrBuilder {
    // Use UserRequest.newBuilder() to construct.
    private UserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserRequest() {
      uid_ = "";
      updateDt_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 16: {

              updateDt_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.PullUserRequestOuterClass.internal_static_mars_stn_UserRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.PullUserRequestOuterClass.internal_static_mars_stn_UserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.class, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <code>string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATE_DT_FIELD_NUMBER = 2;
    private long updateDt_;
    /**
     * <code>int64 update_dt = 2;</code>
     */
    public long getUpdateDt() {
      return updateDt_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (updateDt_ != 0L) {
        output.writeInt64(2, updateDt_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (updateDt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, updateDt_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest other = (win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest) obj;

      boolean result = true;
      result = result && getUid()
          .equals(other.getUid());
      result = result && (getUpdateDt()
          == other.getUpdateDt());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + UPDATE_DT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateDt());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mars.stn.UserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mars.stn.UserRequest)
        win.liyufan.im.proto.PullUserRequestOuterClass.UserRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.PullUserRequestOuterClass.internal_static_mars_stn_UserRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.PullUserRequestOuterClass.internal_static_mars_stn_UserRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.class, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder.class);
      }

      // Construct using win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";

        updateDt_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.PullUserRequestOuterClass.internal_static_mars_stn_UserRequest_descriptor;
      }

      public win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest getDefaultInstanceForType() {
        return win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.getDefaultInstance();
      }

      public win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest build() {
        win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest buildPartial() {
        win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest result = new win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest(this);
        result.uid_ = uid_;
        result.updateDt_ = updateDt_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest) {
          return mergeFrom((win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest other) {
        if (other == win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (other.getUpdateDt() != 0L) {
          setUpdateDt(other.getUpdateDt());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private long updateDt_ ;
      /**
       * <code>int64 update_dt = 2;</code>
       */
      public long getUpdateDt() {
        return updateDt_;
      }
      /**
       * <code>int64 update_dt = 2;</code>
       */
      public Builder setUpdateDt(long value) {
        
        updateDt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 update_dt = 2;</code>
       */
      public Builder clearUpdateDt() {
        
        updateDt_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mars.stn.UserRequest)
    }

    // @@protoc_insertion_point(class_scope:mars.stn.UserRequest)
    private static final win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest();
    }

    public static win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserRequest>
        PARSER = new com.google.protobuf.AbstractParser<UserRequest>() {
      public UserRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserRequest> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PullUserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mars.stn.PullUserRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .mars.stn.UserRequest request = 1;</code>
     */
    java.util.List<win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest> 
        getRequestList();
    /**
     * <code>repeated .mars.stn.UserRequest request = 1;</code>
     */
    win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest getRequest(int index);
    /**
     * <code>repeated .mars.stn.UserRequest request = 1;</code>
     */
    int getRequestCount();
    /**
     * <code>repeated .mars.stn.UserRequest request = 1;</code>
     */
    java.util.List<? extends win.liyufan.im.proto.PullUserRequestOuterClass.UserRequestOrBuilder> 
        getRequestOrBuilderList();
    /**
     * <code>repeated .mars.stn.UserRequest request = 1;</code>
     */
    win.liyufan.im.proto.PullUserRequestOuterClass.UserRequestOrBuilder getRequestOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code mars.stn.PullUserRequest}
   */
  public  static final class PullUserRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mars.stn.PullUserRequest)
      PullUserRequestOrBuilder {
    // Use PullUserRequest.newBuilder() to construct.
    private PullUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PullUserRequest() {
      request_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PullUserRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                request_ = new java.util.ArrayList<win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest>();
                mutable_bitField0_ |= 0x00000001;
              }
              request_.add(
                  input.readMessage(win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          request_ = java.util.Collections.unmodifiableList(request_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.PullUserRequestOuterClass.internal_static_mars_stn_PullUserRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.PullUserRequestOuterClass.internal_static_mars_stn_PullUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest.class, win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private java.util.List<win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest> request_;
    /**
     * <code>repeated .mars.stn.UserRequest request = 1;</code>
     */
    public java.util.List<win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest> getRequestList() {
      return request_;
    }
    /**
     * <code>repeated .mars.stn.UserRequest request = 1;</code>
     */
    public java.util.List<? extends win.liyufan.im.proto.PullUserRequestOuterClass.UserRequestOrBuilder> 
        getRequestOrBuilderList() {
      return request_;
    }
    /**
     * <code>repeated .mars.stn.UserRequest request = 1;</code>
     */
    public int getRequestCount() {
      return request_.size();
    }
    /**
     * <code>repeated .mars.stn.UserRequest request = 1;</code>
     */
    public win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest getRequest(int index) {
      return request_.get(index);
    }
    /**
     * <code>repeated .mars.stn.UserRequest request = 1;</code>
     */
    public win.liyufan.im.proto.PullUserRequestOuterClass.UserRequestOrBuilder getRequestOrBuilder(
        int index) {
      return request_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < request_.size(); i++) {
        output.writeMessage(1, request_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < request_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, request_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest other = (win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest) obj;

      boolean result = true;
      result = result && getRequestList()
          .equals(other.getRequestList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRequestCount() > 0) {
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequestList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mars.stn.PullUserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mars.stn.PullUserRequest)
        win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.PullUserRequestOuterClass.internal_static_mars_stn_PullUserRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.PullUserRequestOuterClass.internal_static_mars_stn_PullUserRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest.class, win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest.Builder.class);
      }

      // Construct using win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          requestBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.PullUserRequestOuterClass.internal_static_mars_stn_PullUserRequest_descriptor;
      }

      public win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest getDefaultInstanceForType() {
        return win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest.getDefaultInstance();
      }

      public win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest build() {
        win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest buildPartial() {
        win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest result = new win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest(this);
        int from_bitField0_ = bitField0_;
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            request_ = java.util.Collections.unmodifiableList(request_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest) {
          return mergeFrom((win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest other) {
        if (other == win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest.getDefaultInstance()) return this;
        if (requestBuilder_ == null) {
          if (!other.request_.isEmpty()) {
            if (request_.isEmpty()) {
              request_ = other.request_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRequestIsMutable();
              request_.addAll(other.request_);
            }
            onChanged();
          }
        } else {
          if (!other.request_.isEmpty()) {
            if (requestBuilder_.isEmpty()) {
              requestBuilder_.dispose();
              requestBuilder_ = null;
              request_ = other.request_;
              bitField0_ = (bitField0_ & ~0x00000001);
              requestBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRequestFieldBuilder() : null;
            } else {
              requestBuilder_.addAllMessages(other.request_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest> request_ =
        java.util.Collections.emptyList();
      private void ensureRequestIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          request_ = new java.util.ArrayList<win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest>(request_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequestOrBuilder> requestBuilder_;

      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public java.util.List<win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest> getRequestList() {
        if (requestBuilder_ == null) {
          return java.util.Collections.unmodifiableList(request_);
        } else {
          return requestBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public int getRequestCount() {
        if (requestBuilder_ == null) {
          return request_.size();
        } else {
          return requestBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest getRequest(int index) {
        if (requestBuilder_ == null) {
          return request_.get(index);
        } else {
          return requestBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public Builder setRequest(
          int index, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestIsMutable();
          request_.set(index, value);
          onChanged();
        } else {
          requestBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public Builder setRequest(
          int index, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          ensureRequestIsMutable();
          request_.set(index, builderForValue.build());
          onChanged();
        } else {
          requestBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public Builder addRequest(win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestIsMutable();
          request_.add(value);
          onChanged();
        } else {
          requestBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public Builder addRequest(
          int index, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequestIsMutable();
          request_.add(index, value);
          onChanged();
        } else {
          requestBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public Builder addRequest(
          win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          ensureRequestIsMutable();
          request_.add(builderForValue.build());
          onChanged();
        } else {
          requestBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public Builder addRequest(
          int index, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          ensureRequestIsMutable();
          request_.add(index, builderForValue.build());
          onChanged();
        } else {
          requestBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public Builder addAllRequest(
          java.lang.Iterable<? extends win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest> values) {
        if (requestBuilder_ == null) {
          ensureRequestIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, request_);
          onChanged();
        } else {
          requestBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public Builder removeRequest(int index) {
        if (requestBuilder_ == null) {
          ensureRequestIsMutable();
          request_.remove(index);
          onChanged();
        } else {
          requestBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder getRequestBuilder(
          int index) {
        return getRequestFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public win.liyufan.im.proto.PullUserRequestOuterClass.UserRequestOrBuilder getRequestOrBuilder(
          int index) {
        if (requestBuilder_ == null) {
          return request_.get(index);  } else {
          return requestBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public java.util.List<? extends win.liyufan.im.proto.PullUserRequestOuterClass.UserRequestOrBuilder> 
           getRequestOrBuilderList() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(request_);
        }
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder addRequestBuilder() {
        return getRequestFieldBuilder().addBuilder(
            win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder addRequestBuilder(
          int index) {
        return getRequestFieldBuilder().addBuilder(
            index, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .mars.stn.UserRequest request = 1;</code>
       */
      public java.util.List<win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder> 
           getRequestBuilderList() {
        return getRequestFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequest.Builder, win.liyufan.im.proto.PullUserRequestOuterClass.UserRequestOrBuilder>(
                  request_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mars.stn.PullUserRequest)
    }

    // @@protoc_insertion_point(class_scope:mars.stn.PullUserRequest)
    private static final win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest();
    }

    public static win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PullUserRequest>
        PARSER = new com.google.protobuf.AbstractParser<PullUserRequest>() {
      public PullUserRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PullUserRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PullUserRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PullUserRequest> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.PullUserRequestOuterClass.PullUserRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mars_stn_UserRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mars_stn_UserRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mars_stn_PullUserRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mars_stn_PullUserRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027pull_user_request.proto\022\010mars.stn\"-\n\013U" +
      "serRequest\022\013\n\003uid\030\001 \001(\t\022\021\n\tupdate_dt\030\002 \001" +
      "(\003\"9\n\017PullUserRequest\022&\n\007request\030\001 \003(\0132\025" +
      ".mars.stn.UserRequestB1\n\024win.liyufan.im." +
      "protoB\031PullUserRequestOuterClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mars_stn_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mars_stn_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mars_stn_UserRequest_descriptor,
        new java.lang.String[] { "Uid", "UpdateDt", });
    internal_static_mars_stn_PullUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mars_stn_PullUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mars_stn_PullUserRequest_descriptor,
        new java.lang.String[] { "Request", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
