// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer_group_request.proto

package win.liyufan.im.proto;

public final class TransferGroupRequestOuterClass {
  private TransferGroupRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransferGroupRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mars.stn.TransferGroupRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string group_id = 1;</code>
     */
    java.lang.String getGroupId();
    /**
     * <code>string group_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <code>int32 line = 2;</code>
     */
    int getLine();

    /**
     * <code>string new_owner = 3;</code>
     */
    java.lang.String getNewOwner();
    /**
     * <code>string new_owner = 3;</code>
     */
    com.google.protobuf.ByteString
        getNewOwnerBytes();

    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    boolean hasNotifyContent();
    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    win.liyufan.im.proto.MessageContentOuterClass.MessageContent getNotifyContent();
    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder getNotifyContentOrBuilder();
  }
  /**
   * Protobuf type {@code mars.stn.TransferGroupRequest}
   */
  public  static final class TransferGroupRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mars.stn.TransferGroupRequest)
      TransferGroupRequestOrBuilder {
    // Use TransferGroupRequest.newBuilder() to construct.
    private TransferGroupRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransferGroupRequest() {
      groupId_ = "";
      line_ = 0;
      newOwner_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TransferGroupRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 16: {

              line_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              newOwner_ = s;
              break;
            }
            case 34: {
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder subBuilder = null;
              if (notifyContent_ != null) {
                subBuilder = notifyContent_.toBuilder();
              }
              notifyContent_ = input.readMessage(win.liyufan.im.proto.MessageContentOuterClass.MessageContent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(notifyContent_);
                notifyContent_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return win.liyufan.im.proto.TransferGroupRequestOuterClass.internal_static_mars_stn_TransferGroupRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return win.liyufan.im.proto.TransferGroupRequestOuterClass.internal_static_mars_stn_TransferGroupRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest.class, win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest.Builder.class);
    }

    public static final int GROUP_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object groupId_;
    /**
     * <code>string group_id = 1;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <code>string group_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LINE_FIELD_NUMBER = 2;
    private int line_;
    /**
     * <code>int32 line = 2;</code>
     */
    public int getLine() {
      return line_;
    }

    public static final int NEW_OWNER_FIELD_NUMBER = 3;
    private volatile java.lang.Object newOwner_;
    /**
     * <code>string new_owner = 3;</code>
     */
    public java.lang.String getNewOwner() {
      java.lang.Object ref = newOwner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        newOwner_ = s;
        return s;
      }
    }
    /**
     * <code>string new_owner = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNewOwnerBytes() {
      java.lang.Object ref = newOwner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newOwner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOTIFY_CONTENT_FIELD_NUMBER = 4;
    private win.liyufan.im.proto.MessageContentOuterClass.MessageContent notifyContent_;
    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    public boolean hasNotifyContent() {
      return notifyContent_ != null;
    }
    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    public win.liyufan.im.proto.MessageContentOuterClass.MessageContent getNotifyContent() {
      return notifyContent_ == null ? win.liyufan.im.proto.MessageContentOuterClass.MessageContent.getDefaultInstance() : notifyContent_;
    }
    /**
     * <code>.mars.stn.MessageContent notify_content = 4;</code>
     */
    public win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder getNotifyContentOrBuilder() {
      return getNotifyContent();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, groupId_);
      }
      if (line_ != 0) {
        output.writeInt32(2, line_);
      }
      if (!getNewOwnerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, newOwner_);
      }
      if (notifyContent_ != null) {
        output.writeMessage(4, getNotifyContent());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, groupId_);
      }
      if (line_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, line_);
      }
      if (!getNewOwnerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, newOwner_);
      }
      if (notifyContent_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getNotifyContent());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest)) {
        return super.equals(obj);
      }
      win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest other = (win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest) obj;

      boolean result = true;
      result = result && getGroupId()
          .equals(other.getGroupId());
      result = result && (getLine()
          == other.getLine());
      result = result && getNewOwner()
          .equals(other.getNewOwner());
      result = result && (hasNotifyContent() == other.hasNotifyContent());
      if (hasNotifyContent()) {
        result = result && getNotifyContent()
            .equals(other.getNotifyContent());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + LINE_FIELD_NUMBER;
      hash = (53 * hash) + getLine();
      hash = (37 * hash) + NEW_OWNER_FIELD_NUMBER;
      hash = (53 * hash) + getNewOwner().hashCode();
      if (hasNotifyContent()) {
        hash = (37 * hash) + NOTIFY_CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getNotifyContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mars.stn.TransferGroupRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mars.stn.TransferGroupRequest)
        win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return win.liyufan.im.proto.TransferGroupRequestOuterClass.internal_static_mars_stn_TransferGroupRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return win.liyufan.im.proto.TransferGroupRequestOuterClass.internal_static_mars_stn_TransferGroupRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest.class, win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest.Builder.class);
      }

      // Construct using win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        groupId_ = "";

        line_ = 0;

        newOwner_ = "";

        if (notifyContentBuilder_ == null) {
          notifyContent_ = null;
        } else {
          notifyContent_ = null;
          notifyContentBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return win.liyufan.im.proto.TransferGroupRequestOuterClass.internal_static_mars_stn_TransferGroupRequest_descriptor;
      }

      public win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest getDefaultInstanceForType() {
        return win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest.getDefaultInstance();
      }

      public win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest build() {
        win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest buildPartial() {
        win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest result = new win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest(this);
        result.groupId_ = groupId_;
        result.line_ = line_;
        result.newOwner_ = newOwner_;
        if (notifyContentBuilder_ == null) {
          result.notifyContent_ = notifyContent_;
        } else {
          result.notifyContent_ = notifyContentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest) {
          return mergeFrom((win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest other) {
        if (other == win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest.getDefaultInstance()) return this;
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (other.getLine() != 0) {
          setLine(other.getLine());
        }
        if (!other.getNewOwner().isEmpty()) {
          newOwner_ = other.newOwner_;
          onChanged();
        }
        if (other.hasNotifyContent()) {
          mergeNotifyContent(other.getNotifyContent());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object groupId_ = "";
      /**
       * <code>string group_id = 1;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string group_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string group_id = 1;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string group_id = 1;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <code>string group_id = 1;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private int line_ ;
      /**
       * <code>int32 line = 2;</code>
       */
      public int getLine() {
        return line_;
      }
      /**
       * <code>int32 line = 2;</code>
       */
      public Builder setLine(int value) {
        
        line_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 line = 2;</code>
       */
      public Builder clearLine() {
        
        line_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object newOwner_ = "";
      /**
       * <code>string new_owner = 3;</code>
       */
      public java.lang.String getNewOwner() {
        java.lang.Object ref = newOwner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          newOwner_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string new_owner = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNewOwnerBytes() {
        java.lang.Object ref = newOwner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newOwner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string new_owner = 3;</code>
       */
      public Builder setNewOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        newOwner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string new_owner = 3;</code>
       */
      public Builder clearNewOwner() {
        
        newOwner_ = getDefaultInstance().getNewOwner();
        onChanged();
        return this;
      }
      /**
       * <code>string new_owner = 3;</code>
       */
      public Builder setNewOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        newOwner_ = value;
        onChanged();
        return this;
      }

      private win.liyufan.im.proto.MessageContentOuterClass.MessageContent notifyContent_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.MessageContentOuterClass.MessageContent, win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder, win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder> notifyContentBuilder_;
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public boolean hasNotifyContent() {
        return notifyContentBuilder_ != null || notifyContent_ != null;
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public win.liyufan.im.proto.MessageContentOuterClass.MessageContent getNotifyContent() {
        if (notifyContentBuilder_ == null) {
          return notifyContent_ == null ? win.liyufan.im.proto.MessageContentOuterClass.MessageContent.getDefaultInstance() : notifyContent_;
        } else {
          return notifyContentBuilder_.getMessage();
        }
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public Builder setNotifyContent(win.liyufan.im.proto.MessageContentOuterClass.MessageContent value) {
        if (notifyContentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          notifyContent_ = value;
          onChanged();
        } else {
          notifyContentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public Builder setNotifyContent(
          win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder builderForValue) {
        if (notifyContentBuilder_ == null) {
          notifyContent_ = builderForValue.build();
          onChanged();
        } else {
          notifyContentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public Builder mergeNotifyContent(win.liyufan.im.proto.MessageContentOuterClass.MessageContent value) {
        if (notifyContentBuilder_ == null) {
          if (notifyContent_ != null) {
            notifyContent_ =
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent.newBuilder(notifyContent_).mergeFrom(value).buildPartial();
          } else {
            notifyContent_ = value;
          }
          onChanged();
        } else {
          notifyContentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public Builder clearNotifyContent() {
        if (notifyContentBuilder_ == null) {
          notifyContent_ = null;
          onChanged();
        } else {
          notifyContent_ = null;
          notifyContentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder getNotifyContentBuilder() {
        
        onChanged();
        return getNotifyContentFieldBuilder().getBuilder();
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      public win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder getNotifyContentOrBuilder() {
        if (notifyContentBuilder_ != null) {
          return notifyContentBuilder_.getMessageOrBuilder();
        } else {
          return notifyContent_ == null ?
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent.getDefaultInstance() : notifyContent_;
        }
      }
      /**
       * <code>.mars.stn.MessageContent notify_content = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          win.liyufan.im.proto.MessageContentOuterClass.MessageContent, win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder, win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder> 
          getNotifyContentFieldBuilder() {
        if (notifyContentBuilder_ == null) {
          notifyContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              win.liyufan.im.proto.MessageContentOuterClass.MessageContent, win.liyufan.im.proto.MessageContentOuterClass.MessageContent.Builder, win.liyufan.im.proto.MessageContentOuterClass.MessageContentOrBuilder>(
                  getNotifyContent(),
                  getParentForChildren(),
                  isClean());
          notifyContent_ = null;
        }
        return notifyContentBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mars.stn.TransferGroupRequest)
    }

    // @@protoc_insertion_point(class_scope:mars.stn.TransferGroupRequest)
    private static final win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest();
    }

    public static win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransferGroupRequest>
        PARSER = new com.google.protobuf.AbstractParser<TransferGroupRequest>() {
      public TransferGroupRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TransferGroupRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransferGroupRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransferGroupRequest> getParserForType() {
      return PARSER;
    }

    public win.liyufan.im.proto.TransferGroupRequestOuterClass.TransferGroupRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mars_stn_TransferGroupRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mars_stn_TransferGroupRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034transfer_group_request.proto\022\010mars.stn" +
      "\032\025message_content.proto\"{\n\024TransferGroup" +
      "Request\022\020\n\010group_id\030\001 \001(\t\022\014\n\004line\030\002 \001(\005\022" +
      "\021\n\tnew_owner\030\003 \001(\t\0220\n\016notify_content\030\004 \001" +
      "(\0132\030.mars.stn.MessageContentB6\n\024win.liyu" +
      "fan.im.protoB\036TransferGroupRequestOuterC" +
      "lassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          win.liyufan.im.proto.MessageContentOuterClass.getDescriptor(),
        }, assigner);
    internal_static_mars_stn_TransferGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mars_stn_TransferGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mars_stn_TransferGroupRequest_descriptor,
        new java.lang.String[] { "GroupId", "Line", "NewOwner", "NotifyContent", });
    win.liyufan.im.proto.MessageContentOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
